#!/usr/bin/env python3
"""Build tokens.css from frappe-ui's generated design tokens.

Reproduces frappe-ui's own CSS-variable contract byte-for-byte
(`tailwind/colorPalette.js#generateCSSVariables` + radius/typography), so
graphics built here match Frappe products 1:1. Then layers video-specific
brand aliases on top: violet as the accent, dark theme as the default.

Sources live in ./frappe-ui-tokens/ (copied from the frappe-ui checkout — see
PROVENANCE.txt). Re-run after refreshing those:

    python3 build_tokens.py

Output: ./tokens.css  (import it in every composition's <head>)
"""
import json
import pathlib

HERE = pathlib.Path(__file__).parent
SRC = HERE / "frappe-ui-tokens"
OUT = HERE / "tokens.css"

colors = json.loads((SRC / "colors.json").read_text())
typography = json.loads((SRC / "typography.json").read_text())
radius = json.loads((SRC / "radius.json").read_text())

MODE = {
    "lightMode": colors["lightMode"],
    "darkMode": colors["darkMode"],
    "overlay": colors["overlay"],
    "neutral": colors["neutral"],
}


def resolve(ref):
    """Resolve a themedVariables reference like 'darkMode/gray/950'."""
    parts = ref.split("/")
    mode, color = parts[0], parts[1]
    if mode == "neutral":
        return MODE["neutral"][color]
    return MODE[mode][color][parts[2]]


def semantic_block(mode_key):
    """Emit --{category}-{name} for surface/ink/outline of one theme."""
    lines = []
    for category, entries in colors["themedVariables"][mode_key].items():
        for name, ref in entries.items():
            lines.append(f"  --{category}-{name}: {resolve(ref)};")
    return "\n".join(lines)


def primitive_block(mode_key, prefix=""):
    """Emit --{prefix}{hue}-{shade} for every primitive shade of one mode."""
    lines = []
    for hue, shades in colors[mode_key].items():
        for shade, hexv in shades.items():
            lines.append(f"  --{prefix}{hue}-{shade}: {hexv};")
    return "\n".join(lines)


def radius_block():
    lines = []
    for key, value in radius.items():
        if key == "DEFAULT":
            continue  # frappe-ui skips --radius-DEFAULT (awkward name)
        lines.append(f"  --radius-{key}: {value};")
    return "\n".join(lines)


# Brand aliases: violet is the accent. Steps reference the primitives so they
# theme-flip automatically (--violet-* under :root, --dark-violet-* under dark).
BRAND_LIGHT = """\
  /* brand = violet (frappe-ui badge accent) */
  --brand: var(--violet-500);
  --brand-hover: var(--violet-600);
  --brand-subtle: var(--violet-100);
  --brand-ink: var(--violet-600);      /* violet text on light surface */
  --on-brand: #ffffff;                 /* text on a violet fill */"""

BRAND_DARK = """\
  --brand: var(--dark-violet-500);
  --brand-hover: var(--dark-violet-400);
  --brand-subtle: var(--dark-violet-900);
  --brand-ink: var(--dark-violet-300);
  --on-brand: #ffffff;"""

# Typography (frappe-ui espresso)
fw = typography["fontWeight"]
TYPO = f"""\
  --font-text: "Inter", "Inter Variable", system-ui, sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, monospace;
  --fw-regular: {fw['regular']};
  --fw-medium: {fw['medium']};
  --fw-semibold: {fw['semibold']};
  --fw-bold: {fw['bold']};
  --fw-black: {fw['black']};"""

css = f"""/* AUTO-GENERATED by build_tokens.py — do not edit by hand.
   Source: frappe/frappe-ui espresso tokens (see frappe-ui-tokens/PROVENANCE.txt).
   Variable names match frappe-ui 1:1 (--surface-*, --ink-*, --outline-*,
   --{{hue}}-{{shade}} light / --dark-{{hue}}-{{shade}} dark, --radius-*).
   Video brand: violet accent, DARK theme is the default (see :root below). */

/* Default the whole system to DARK. Add data-theme="light" to opt a subtree
   back to light. frappe-ui ships :root=light/[data-theme=dark]=dark; we invert
   the default for video by mirroring the dark values into :root as well. */

:root {{
{radius_block()}
{TYPO}
}}

/* ---- LIGHT (opt-in: <html data-theme="light">) ---- */
[data-theme="light"] {{
{semantic_block('light')}
{primitive_block('lightMode')}
{BRAND_LIGHT}
}}

/* ---- DARK (default) ---- */
:root,
[data-theme="dark"] {{
{semantic_block('dark')}
{primitive_block('darkMode', prefix='dark-')}
{BRAND_DARK}
}}

/* Also expose the canonical (light-scale) primitives everywhere so a graphic
   can reach a specific hue step regardless of theme, e.g. var(--violet-500). */
:root {{
{primitive_block('lightMode')}
}}
"""

OUT.write_text(css)
print(f"wrote {OUT} ({len(css.splitlines())} lines)")
print(f"  surface/ink/outline (dark default) + {len(colors['darkMode'])} hue scales")
print(f"  brand = violet | radius {len(radius)-1} steps | Inter typography")
